name: Build Sammad Keyboard APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build Android APK
      run: |
        msbuild /p:Configuration=Release /t:SignAndroidPackage /p:AndroidBuildApplicationPackage=true

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SammadKeyboard-APK
        path: |
          **/*.apk
          
